spring.config.import=optional:file:/config/application.properties,optional:file:/secret-config/application.secret.properties

application.properties.from.configmap=
application.secret.properties.from.secret=

