apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-config
  labels:
    {{- include "backend-parameters.labels" . | nindent 4 }}
data:
  ENV_VAR1: "custom_value_from_configmap"
  application.properties: |
    application.properties.from.configmap=value-from-configmap
