apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-env
  labels:
    {{- include "backend-parameters.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENV_VAR2: "secret_value_2"
  ENV_VAR3: "secret_value_3"