apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "backend-parameters.labels" . | nindent 4 }}
type: Opaque
stringData:
  application.secret.properties: |
    application.secret.properties.from.secret=value-from-secret
