apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
  labels:
    {{- include "backend-parameters.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENV_VAR4: "value4"
  application.secret.properties: "application.secret.properties.from.secret=server.port=8080\\nlogging.level.root=INFO\\n\n"

